export const ruData = [
  {
    id: 1,
    level: 0,
    name: 'Би-2',
    species: 'Я никому не верю',
    description: '«Би-2» — белорусская и российская рок-группа, образованная в 1988 году в Бобруйске. Основатели и бессменные участники — Шура Би-2 (гитара, вокал) и Лёва Би-2 (основной вокал). В состав команды в 2022 году также входят Андрей Звонков (гитара), Макс Лакмус (бас-гитара), Борис Лифшиц (ударные, перкуссия) и Ян Николенко (бэк-вокал, клавишные, флейта, перкуссия)',
    image: 'https://triboona.ru/uploads/posts/2022-10/1666280429-11.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/Bi-2_-_YA_nikomu_ne_veryu_(musmore.com).mp3',
  },
  {
    id: 2,
    level: 0,
    name: 'Макс Корж',
    species: 'Свой дом',
    description: 'Макси́м Анато́льевич Корж — белорусский певец, автор песен и композитор.Во время учёбы в Белорусском государственном университете записал свою первую сольную песню. Проучившись в БГУ до второго курса, решил, что учёба мешает музыке, бросил университет и всерьёз занялся музыкальной деятельностью. Летом 2012 года Макс Корж выпустил первый альбом под названием «Животный мир». В альбом вошло 16 песен, слова которых написал сам певец. ',
    image: 'https://tntmusic.ru/media/content/article/2021-12-19_09-18-30__a1d56712-60ac-11ec-a43d-a7fd32614fe4.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/Макс Корж - Свой Дом.mp3',
  },
  {
    id: 3,
    level: 0,
    name: 'IOWA',
    species: 'Знаки',
    description: 'IOWA — белорусско-российская поп-группа, образована в 2009 году в Могилёве, где музыканты изначально играли альтернативный рок с элементами хард-рока. Название дано в честь одноименного альбома группы Slipknot',
    image: 'https://www.sb.by/upload/iblock/7c1/7c1c90819400c46b3506de9da8f5a476.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/IOWA_-_Znaki_(musmore.com).mp3',
  },
  {
    id: 4,
    level: 0,
    name: 'Тима Белору́сских',
    species: 'Алёнка',
    description: 'Тима Белорусских — белорусский певец, автор песен, композитор и музыкант. Сольную карьеру начал в 2017 году. Первую известность получил в 2018 году благодаря песне «Мокрые кроссы»',
    image: 'https://vokrug.tv/pic/news/d/3/c/c/d3ccc7a191a90eaab28463c639ffc4dd.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/Tima_Belorusskikh_-_Aljonka_(musmore.com).mp3',
  },
  {
    id: 5,
    level: 0,
    name: 'Ляпис Трубецкой',
    species: 'Грай',
    description: 'Ляпис Трубецкой — советская и белорусская панк-рок-группа, образовалась в сентябре 1989 года в Минске.Группа названа в честь комического героя романа Ильи Ильфа и Евгения Петрова «Двенадцать стульев», поэта-халтурщика Никифора Ляписа, который печатался под псевдонимом Трубецкой',
    image: 'https://hvali.by/wp-content/uploads/2014/09/lyapis-mitrofanova02.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/Lyapis_Trubeckojj_-_Grajj_(musmore.com).mp3',
  },
  {
    id: 6,
    level: 0,
    name: 'Леприконсы',
    species: 'Хали-гали, паратрупер',
    description: 'Леприконсы — белорусская поп-панк-группа, была создана 1 сентября 1996 года. Основателем, лидером, автором большей части композиций и вокалистом коллектива является Илья Митько',
    image: 'https://dorognoe.ru/thumb/performers_870/images/singers/00/2017/2e/47/58c91908aefcd_5811bc0f8ea21_photo_15281_0.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/Leprikonsy_-_KHali-gali_paratruper_(musmore.com).mp3',
  },
  {
    id: 7,
    level: 1,
    name: 'Грязь',
    species: 'Я ненавижу людей',
    description: 'Грязь — белорусская рэп-группа из Могилёва. Коллектив был образован в 2011 году вокалистом Денисом Астаповым и битмейкером Романом "Англичанином" Сащеко. 14 сентября 2018 года вышел дебютный студийный альбом "Сундук мертвеца"',
    image: 'https://34mag.net/piarshak/content/editor_images/2019content/august/gryaz/1_1.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/Gryaz_-_YA_nenavizhu_lyudejj_(musmore.com).mp3',
  },
  {
    id: 8,
    level: 1,
    name: 'ЛСП',
    species: 'Не убежал',
    description: 'Олег Вади́мович Савченко более известный под сценическим псевдонимом ЛСП — белорусский певец, рэпер и автор песен. Сольную карьеру начал в 2007 году, с тех пор выпустив три мини-альбома и шесть студийных альбомов. Работал в тесном сотрудничестве с могилёвским продюсером Романом Саще́нко как одноимённый дуэт «ЛСП»',
    image: 'https://youknow.by/resource/images/2019/10/lsp2.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/LSP_-_Ne_ubezhal_(musmore.com).mp3',
  },
  {
    id: 9,
    level: 1,
    name: 'Iva Sativa',
    species: 'Коса',
    description: "Iva Sativa - хип-хоп исполнительница родом из Борисова (Беларусь), автор песен, продюсер. Творческие работы Ивы написаны преимущественно на беларусском языке, жанр можно описать как инди-фолк-хоп. Победитель Jager Music Awards 2021 в номинации «People's Choice».",
    image: 'https://34mag.net/piarshak/content/editor_images/2021content/sativa/iva-10.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/Iva Sativa - Коса.mp3',
  },
  {
    id: 10,
    level: 1,
    name: 'Belaroots',
    species: 'Могила льва',
    description: 'Belaroots - рэп-группа,которую основали в Минске белорусские реперы Angst, Zeman и Kontra. В начале 2017 года вышел их дебютный альбом "Однокоренные".',
    image: 'https://i.c97.org/p/articles/2017/ai-237587-aux-head-20170113_belaroots_360.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/BELAROOTS - Магіла льва.mp3',
  },
  {
    id: 11,
    level: 1,
    name: 'Vinsent',
    species: 'Ток',
    description: 'Vinsent (настоящее имя — Дмитрий Владимирович Папко) — белорусский певец, хип-хоп исполнитель, актёр. Пишет и исполняет песни на белорусском языке. Изначально выступал самостоятельно, в настоящее время — в составе коллектива, под живое музыкальное сопровождение.',
    image: 'https://naviny.belsat.eu/wp-content/uploads/2015/11/867678.png',
    audio: 'https://yazykovadaria.github.io/mysic//rap/vinsent.mp3',
  },
  {
    id: 12,
    level: 1,
    name: ' IQ48',
    species: 'Сьвятло ў цемры',
    description: 'IQ48 — группа из Минска, сочетающая в своем творчестве рок, фанк и рэп. Первоначально группа была создана осенью 2001 года как дуэт вокалиста Павла «Фрейда» Зыгмантовича и гитариста Евгения «Буззы» Бузовского. Далее к ним присоединился второй вокалист Александр «Эш» Раковец, бас-гитарист Константин Колесников и барабанщик Антон «Сатана» Мацулевич',
    image: 'https://lastfm.freetls.fastly.net/i/u/ar0/3843555589034a6d871a45d943082ae5.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/IQ48 - Сьвятло ў цемры (dizer.net).mp3',
  },
  {
    id: 13,
    level: 2,
    name: 'Бачу ўпершыню',
    species: 'Менск вясной',
    description: 'Бачу ўпершыню - белорусский поп-дуэт, основанный в 2013 году вокалистом Алесем Сьнег и гитаристом Владиславом Лепешинским ',
    image: 'https://sun9-8.userapi.com/impf/c834300/v834300931/1332a8/7WdjDfonF1A.jpg?size=604x403&quality=96&sign=78cf5c52c330be88bafeab42012cc1ba&type=album',
    audio: 'https://yazykovadaria.github.io/mysic//pop/Бачу Ўпершыню - Менск Вясной.mp3',
  },
  {
    id: 14,
    level: 2,
    name: 'Litesound',
    species: 'We Are The Heroes',
    description: 'Litesound — интернациональная группа, образованная братьями Дмитрием и Владимиром Карякиными в Минске в 2005 году. В 2006 выпустили трек "Solo Per Te", который попал в горячую радиоротацию как в Беларуси, так и в Италии.Litesound пять раз принимали участие в национальных отборах на конкурс «Евровидение», трижды проходя в финал и дважды занимая второе место.',
    image: 'https://i1.sndcdn.com/avatars-000449391813-hfsa6f-t500x500.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/Litesound - We Are The Heroes (Евровидение 2012 Беларусь).mp3',
  },
  {
    id: 15,
    level: 2,
    name: 'Michael Soul',
    species: 'Humanize',
    description: 'Michael Soul (настю имя — Михаил Сосунов) — белорусский певец и автор песен. Полуфиналист восьмого сезона украинского шоу «Голос страны». Также участвовал в телепроектах «X-Фактор», «Хочу к Меладзе» и «Лига смеха». В 2018 году выпустил мини-альбом «INSIDE», состоящий из 5 англоязычных треков',
    image: 'https://static.nv.ua/shared/system/MediaPhoto/images/000/220/494/medium/9541b030bb10fd88d4d1198abdd71365.png?q=85&stamp=20220211160431&f=jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/Michael Soul - Humanize.mp3',
  },
  {
    id: 16,
    level: 2,
    name: 'VAL',
    species: 'Да видна',
    description: 'VAL (наст. имя Валерия Грибусова) — белорусская певица, музыкант и автор песен. Свой дебютный сингл «Кто ты есть» выпустила 1 мая 2016 года. В январе 2017 года состоялся релиз дебютного клипа на сингл «Ветер во сне»',
    image: 'https://esckaz.com/2020/JsiJ-6HwEu4.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/VAL-Da Vidna.mp3',
  },
  {
    id: 17,
    level: 2,
    name: 'NaviBand',
    species: 'Іншымі',
    description: 'NaviBand — белорусская музыкальная группа из Минска. Коллектив был образован в 2013 году и первоначально существовал в виде дуэта Ксении Жук и Артёма Лукьяненко под названием NAVI. Первая совместно записанная песня «Абдымi мяне» сразу же стала радиохитом в Белоруссии, что и послужило началом карьеры дуэта.',
    image: 'https://modernrock.ru/wp-content/uploads/2019/11/naviband.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/NaviBand_-_nshym_(musmore.com).mp3',
  },
  {
    id: 18,
    level: 2,
    name: 'Лиса',
    species: 'Не Відпускай',
    description: 'Лиса (наст. имя Лиза Костенко) - булорусская певица и автор песен. Дебютный сингл «Сны» вышел в 2018 году,тогда же состоялась премьера мини-альбома «Бархат». В марте 2020 выпустила первый клип, а в апреле состоялся релиз четвертого альбома - «Вельвет».',
    image: 'https://34mag.net/piarshak/media/posts/5e6a3f700398c-620-lisa-c.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/Лиса - Не Відпускай.mp3',
  },
  {
    id: 19,
    level: 3,
    name: 'N.R.M.',
    species: 'Паветраны шар',
    description: 'N.R.M. (белор. Незалежная Рэспубліка Мроя) — белорусская рок-группа, основанная в Минске в 1994 году участниками рок-группы «Мроя». Коллектив исполняет песни на белорусском языке, а при написании текстов часто использует белорусскую латинку',
    image: 'https://lastfm.freetls.fastly.net/i/u/ar0/6ab59e63e61b448e9ab0585d6683b726.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/nrm-pavetrany-shar.mp3',
  },
  {
    id: 20,
    level: 3,
    name: 'Без билета',
    species: 'Адрес - планета Земля',
    description: 'Без билета — белорусская рок-группа, образованная в 1999 году в Минске. В раннем творчестве музыканты пели на белорусском языке в стиле фолк-рок, совмещая инди-рок с психоделическими элементами. В 2003—2006 годы основным стилем группы стал инди-рок. В 2007 году вышел альбом «Кино» в жанре поп-рок и альт-поп',
    image: 'https://modernrock.ru/wp-content/uploads/2018/08/bez-bileta.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/bez-bileta-adres---planeta-zemlya.mp3',
  },
  {
    id: 21,
    level: 3,
    name: 'J:МОРС',
    species: 'Піва',
    description: 'J:МОРС — белорусская рок-группа, основанная в 1999 году в Минске. Изначально группа называлась «No Logo». Это был дуэт студентов-юристов Владимира Пугача и Артёма Ледовского. В 1999 году к ним присоединился гитарист Роман Орлов, который предложил сменить название. В результате было выбрано слово «морс», к которому добавили букву «J». Существует версия, что название группы связано с именем гитариста группы «Deep Purple» Стивом Дж. Морсом.',
    image: 'https://strigaproduction.com/wp-content/uploads/2022/04/J-MORS-JAN-20195463.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/j-mors-p-va-2003.mp3',
  },
  {
    id: 22,
    level: 3,
    name: 'Náka',
    species: 'Бяжы',
    description: 'Náka — белорусская рок-группа, созданная в 2004 г. в Минске. В состав группы вошли: Анастасия Шпаковская (вокал, фортепиано), Юрий Сизов (ударные), Сергей Щурко (гитара). В 2005 г. выпустили первый live-клип на песню «Хочу уснуть я»',
    image: 'https://studlive.by/wp-content/uploads/2016/01/naka-group.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/kopiya-naka-byazhy.mp3',
  },
  {
    id: 23,
    level: 3,
    name: 'Nizkiz',
    species: 'Блізка',
    description: 'Nizkiz — белорусская рок-группа, исполняющая песни на русском и белорусском языках. Создана в 2008 году в Могилёве. Первая белорусская группа, издавшая альбом в цифровом формате 3plet.',
    image: 'https://img08.rl0.ru/afisha/e904x508p0x0f1815x1036q85i/s3.afisha.ru/mediastorage/e9/fe/b2c64be23c534953a2c0a35afee9.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/Nizkiz_-_Blzka_(musmore.com).mp3',
  },
  {
    id: 24,
    level: 3,
    name: 'Akute',
    species: 'Калi б я застаўся з табою',
    description: 'Akute (Акутэ) — белорусская рок-группа,cоздана в 2008 году бывшими участниками могилевской альтернативной группы «Глюки» Стасом Мытником и Романом Жигаревым. Первое выступление группы состоялось в августе 2009 г. на фестивале «Приход». В ноябре того же года на популярном белорусскоязычном сайте «Тузін Гітоў» состоялась премьера первой студийной записи коллектива — песни «Адзіноцтва»',
    image: 'https://lastfm.freetls.fastly.net/i/u/ar0/3d9a5d047bb71c2c6365992174022be0.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/akute-kali-b-ya-zasta-sya-z-taboyu.mp3',
  },
  {
    id: 25,
    level: 4,
    name: 'Кассиопея',
    species: 'Щупальце с планеты "Х"',
    description: 'Кассиопея — белорусская электронная инди-поп-группа, основанная в 2001 году в Минске. Состоит из трёх человек, имеет в послужном списке три официальных альбома. Группу отличает характерное чувство юмора, научно-фантастическая и абсурдистская тематика. На сцене они, как правило, выступают в причудливых костюмах и масках: единственный повторяющийся из образа в образ атрибут — накладные усы, а остальные детали концертного гардероба регулярно меняются',
    image: 'https://sun9-45.userapi.com/impg/0zl8x0MmTDHcPXj3ct9Wek_M0ihmyBQz7SCozw/WOhRbxbtuBc.jpg?size=604x451&quality=95&sign=e1d391bf30240a1c6c3d5116c7e06e48&type=album',
    audio: 'https://yazykovadaria.github.io/mysic//indi/kassiopeya-schupal-ce-s-planety-h.mp3',
  },
  {
    id: 26,
    level: 4,
    name: 'СОЮЗ',
    species: 'Офисная',
    description: 'СОЮЗ – беларусская группа из Минска, которая сложилась из музыкантов, игравших в Young and Dramatic, Applepicker и White Cave, The Toobes и «Валентин Стрыкало. В 2018 выпустили дебютный альбом – «Это все совсем не то»',
    image: 'https://34mag.net/piarshak/media/posts/5b28d96d300f6-620-soyuz.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//indi/СОЮЗ - Офисная.mp3',
  },
  {
    id: 27,
    level: 4,
    name: 'Молчат дома',
    species: 'Я не коммунист',
    description: 'Музыкальный проект «Молчат дома» был образован в Минске в 2017 году. Основателями являются Егор Шкутко и Роман Комогорцев. В апреле 2017 года был выпущен дебютный альбом под названием «С крыш наших домов», в который вошли 9 треков. В 2018 году в свет выходит альбом, получивший название «Этажи», который вошел в двадцатку лучших альбомов 2018 года по версии британских критиков.',
    image: 'https://img.the-village.ru/6qUhkpLABcMINbZGAoS-uuc3V2o8uEKxzH1GwsFIx0c/rs:fill:940:630/q:88/plain/2021/04/13/94IMG_9382.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//indi/Molchat_Doma_-_YA_ne_kommunist_(musmore.com).mp3',
  },
  {
    id: 28,
    level: 4,
    name: 'Palina',
    species: 'Месяц',
    description: 'Palina — творческий псевдоним белорусской исполнительницы Полины Полонейчик. Родилась в Минске в апреле 1994 года.Приобрела известность после победы на фестивале «Бардовская осень» в 2011 году. В 2012 году стала лауреатом премии Ultra-Music Awards в номинации «Открытие года»',
    image: 'https://34mag.net/piarshak/content/editor_images/2020content/december/palina/PALINAKREMENDYNAMIT2.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//indi/Palina_-_Mesyac_(musmore.com).mp3',
  },
  {
    id: 29,
    level: 4,
    name: 'Intelligency',
    species: 'Malitva Belaruskaja',
    description: 'Intelligency  — белорусский многоязычный музыкальный коллектив, играющий в стиле техно-поп. Группа основана 9 мая 2013 года Всеволодом Довбней и Юрием Тарасевичем. Первый студийный альбом назывался Doloven и появился в конце 2015 года',
    image: 'https://34mag.net/piarshak/media/posts/5edf7a4f24081-620-int-aug.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//indi/Intelligency_-_Malitva_Belaruskaja_(musmore.com).mp3',
  },
  {
    id: 30,
    level: 4,
    name: 'Dlina Volny',
    species: 'Do it',
    description: 'Dlina Volny — музыкальное трио из Минска. Играют музыку в жанрах нью-вейв, пост-панк, синт-поп, брут-поп. Группа образовалась в 2016 году, в мае того же года был выпущен дебютный релиз «Neizmerima»',
    image: 'https://289118.selcdn.ru//media/artists/0/0/1/1488/20200504054601_large_dlina_volny.jpeg',
    audio: 'https://yazykovadaria.github.io/mysic//indi/Dlina_Volny_-_Do_It_(musmore.com).mp3',
  },
  {
    id: 31,
    level: 5,
    name: 'Петля Пристрастия',
    species: 'Автоматизм',
    description: 'Петля Пристрастия (белор. Пятля Прыхільнасьці) — белорусская пост-панк-группа из Минске. Была образована в 2004 году вокалистом Ильёй Черепко-Самохваловым и басистом Тимофеем Савицким на обломках предыдущего проекта «Полипы». По словам Ильи, название группы было взято с советского антиалкогольного плаката, который он увидел в поликлинике. В 2009 г.вышел дебютный альбом группы под названием «Всем доволен»',
    image: 'https://trll.ru/uploads/2013/04/petp1.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pank/Petlya_Pristrastiya_-_Avtomatizm_(musmore.com).mp3',
  },
  {
    id: 32,
    level: 5,
    name: 'Разбітае сэрца пацана',
    species: 'БРСМ',
    description: 'Разбітае сэрца пацана («РСП») — Белорусский музыкальный коллектив, основанный в конце 1990-х в стенах Университета культуры. Основателями выступили два студента: Денис Тарасенко, известный по группе «Склеп» и Саша Маленький (впоследствии известный как DJ Тим Карамыслов). Группа отличается тем, что пишет и исполняет свои песни на трасянке',
    image: 'https://cdn.3bls.eu/wp-content/uploads/2021/09/241085226_348843100277822_2432580024769766270_n-570x270.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pank/razbitoe_serdce_pacana_-_brsm_(z2.fm).mp3',
  },
  {
    id: 33,
    level: 5,
    name: 'Дай дарогу!',
    species: 'Про ментов',
    description: 'Дай дарогу! — белорусская панк-рок-группа из Бреста. Была образована в мае 1998 года в Бресте Юрием «Кешей» Стыльским (музыка, тексты, гитара, вокал) и Василием Копыловым (музыка, тексты, вокал). В июне 1999 г. выпустили дебютный альбом «Зарубило!»',
    image: 'https://34mag.net/piarshak/media/posts/5e456ae0d79f0-5bae3737d66fc-620-dd.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pank/day-darogu-pro-mentov.mp3',
  },
  {
    id: 34,
    level: 5,
    name: 'Contra La Contra',
    species: 'Ты будешь счастлив и доволен',
    description: 'Contra La Contra — белорусская панк-рок-группа, основанная в 2001 году в Гродно. За время своего существование группа успела выпустить две пластинки: демо «Выйди на улицу» в 2001 г. и альбом «Ни слова о политике!» в 2002 г.',
    image: 'https://sun9-25.userapi.com/c4338/u68263679/130334231/x_566f6a93.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pank/Contra_La_Contra_Ty_budesh_schastliv_i_dovolen.mp3',
  },
  {
    id: 35,
    level: 5,
    name: 'Мутнаевока',
    species: 'Мутныя вочы',
    description: 'Мутнаевока — белорусская группа, исполняющая песни на белорусском языке. Создана в 2005 году в Минске. Музыкальное направление включает в себя альтернативный рок, авангард-рок, пост-панк. Выход дебютного альбома «Пошлы гламур» в 2010 году стал отправной точкой в творчестве группы. Помимо этого альбома, в дискографию группы входят ЕР «Усе мае сябры» (2011), ЕР «Ліхаманка» (2012) и ЕР «Апантаны» (2014)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/37/%D0%9C%D0%B2.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pank/mutnaevoka_-_mutnija_vochi_(z2.fm).mp3',
  },
  {
    id: 36,
    level: 5,
    name: 'Dzieciuki',
    species: 'Партызан',
    description: 'Dzieciuki — белорусская фолк-панк группа, основанная в 2012 году в Гродно. Исполняет песни на белорусском языке в основном на историческую тематику. Первый полноценный альбом «Гарадзенскі гармідар» (с белор. — «Гродненское толпотворение») вышел в феврале 2014 г. Периодически выступления группы подвергаются запретам.',
    image: 'https://rocketsmusic.ru/sites/default/files/styles/max_1300x1300/public/field/image/Dzieciuki.jpg.webp?itok=UObvym_x',
    audio: 'https://yazykovadaria.github.io/mysic//pank/Dzieciuki_-_Partyzan_(musmore.com).mp3',
  },
];

export const byData = [
  {
    id: 1,
    level: 0,
    name: 'Бi-2',
    species: 'Я никому не верю',
    description: '«Би-2» — беларускі і расійскі рок-гурт, утвораны ў 1988 годзе ў Бабруйску. Заснавальнікі і нязменныя ўдзельнікі - Шура Бі-2 (гітара, вакал) і Лёва Бі-2 (асноўны вакал). У склад каманды ў 2022 годзе таксама ўваходзяць Андрэй Званкоў (гітара), Макс Лакмус (бас-гітара), Барыс Ліфшыц (ударныя, перкусія) і Ян Нікаленка (бэк-вакал, клавішныя, флейта, перкусія).',
    image: 'https://triboona.ru/uploads/posts/2022-10/1666280429-11.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/Bi-2_-_YA_nikomu_ne_veryu_(musmore.com).mp3',
  },
  {
    id: 2,
    level: 0,
    name: 'Макс Корж',
    species: 'Свой дом',
    description: 'Максім Анаталевіч Корж — беларускі спявак, аўтар песень і кампазітар. Падчас вучобы ў Беларускім дзяржаўным універсітэце запісаў сваю першую сольную песню. Правучыўшыся ў БДУ да другога курса, вырашыў, што вучоба перашкаджае музыцы, кінуў універсітэт і сур\'ёзна заняўся музычнай дзейнасцю. Летам 2012 года Макс Корж выпусціў першы альбом пад назвай "Животный мир". У альбом увайшло 16 песень, словы якіх напісаў сам спявак.',
    image: 'https://tntmusic.ru/media/content/article/2021-12-19_09-18-30__a1d56712-60ac-11ec-a43d-a7fd32614fe4.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/Макс Корж - Свой Дом.mp3',
  },
  {
    id: 3,
    level: 0,
    name: 'IOWA',
    species: 'Знаки',
    description: 'IOWA — беларуска-расійскі поп-гурт, створаны ў 2009 годзе ў Магілёве, дзе музыканты першапачаткова гралі альтэрнатыўны рок з элементамі хард-рока. Назва дадзена ў гонар аднайменнага альбома гурта Slipknot',
    image: 'https://www.sb.by/upload/iblock/7c1/7c1c90819400c46b3506de9da8f5a476.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/IOWA_-_Znaki_(musmore.com).mp3',
  },
  {
    id: 4,
    level: 0,
    name: 'Ціма Беларускіх',
    species: 'Алёнка',
    description: 'Ціма Беларускіх - беларускі спявак, аўтар песень, кампазітар і музыка. Сольную кар\'еру пачаў у 2017 годзе. Першую вядомасць атрымаў у 2018 годзе дзякуючы песні «Мокрые кроссы»',
    image: 'https://vokrug.tv/pic/news/d/3/c/c/d3ccc7a191a90eaab28463c639ffc4dd.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/Tima_Belorusskikh_-_Aljonka_(musmore.com).mp3',
  },
  {
    id: 5,
    level: 0,
    name: 'Ляпiс Трубецкой',
    species: 'Грай',
    description: 'Ляпiс Трубецкой — савецкі і беларускі панк-рок-гурт, які ўтварыўся ў верасні 1989 года ў Мінску.Гурт названы ў гонар камічнага героя рамана Іллі Ільфа і Яўгена Пятрова «Дванаццаць крэслаў», паэта-халтуршчыка Нікіфара Ляпіса, які друкаваўся пад псеўданімам Трубяцкой',
    image: 'https://hvali.by/wp-content/uploads/2014/09/lyapis-mitrofanova02.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/Lyapis_Trubeckojj_-_Grajj_(musmore.com).mp3',
  },
  {
    id: 6,
    level: 0,
    name: 'Лепрыконсы',
    species: 'Хали-гали, паратрупер',
    description: 'Лепрыконсы - беларускі поп-панк-гурт, быў створаны 1 верасня 1996 года. Заснавальнікам, лідэрам, аўтарам большай часткі кампазіцый і вакалістам калектыву з\'яўляецца Ілля Міцько',
    image: 'https://dorognoe.ru/thumb/performers_870/images/singers/00/2017/2e/47/58c91908aefcd_5811bc0f8ea21_photo_15281_0.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/Leprikonsy_-_KHali-gali_paratruper_(musmore.com).mp3',
  },
  {
    id: 7,
    level: 1,
    name: 'Грязь',
    species: 'Я ненавижу людей',
    description: 'Беларускі рэп-гурт з Магілёва. Калектыў быў утвораны ў 2011 годзе вакалістам Дзянісам Астапавым і бітмэйкерам Раманам "Англічанінам" Сашчэка. 14 верасня 2018 года выйшаў дэбютны студыйны альбом "Сундук мертвеца"',
    image: 'https://34mag.net/piarshak/content/editor_images/2019content/august/gryaz/1_1.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/Gryaz_-_YA_nenavizhu_lyudejj_(musmore.com).mp3',
  },
  {
    id: 8,
    level: 1,
    name: 'ЛСП',
    species: 'Не убежал',
    description: 'Алег Вадзімавіч Саўчанка больш вядомы пад сцэнічным псеўданімам ЛСП — беларускі спявак, рэпер і аўтар песень. Сольную кар\'еру пачаў у 2007 годзе, з таго часу выпусціўшы тры міні-альбомы і шэсць студыйных альбомаў. Працаваў у цесным супрацоўніцтве з магілёўскім прадзюсарам Раманам Сашчанкам як аднайменны дуэт «ЛСП»',
    image: 'https://youknow.by/resource/images/2019/10/lsp2.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/LSP_-_Ne_ubezhal_(musmore.com).mp3',
  },
  {
    id: 9,
    level: 1,
    name: 'Iva Sativa',
    species: 'Коса',
    description: "Iva Sativa - хіп-хоп выканаўца родам з Барысава (Беларусь), аўтар песень, прадзюсер. Творчыя працы Івы напісаны пераважна на беларускай мове, жанр можна апісаць як інды-фолк-хоп. Пераможца Jager Music Awards 2021 у намінацыі «People's Choice».",
    image: 'https://34mag.net/piarshak/content/editor_images/2021content/sativa/iva-10.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/Iva Sativa - Коса.mp3',
  },
  {
    id: 10,
    level: 1,
    name: 'Belaroots',
    species: 'Магiла льва',
    description: 'Belaroots - рэп-гурт, які заснавалі ў Мінску беларускія рэперы Angst, Zeman і Kontra. У пачатку 2017 года выйшаў іх дэбютны альбом "Аднакарэнныя"',
    image: 'https://i.c97.org/p/articles/2017/ai-237587-aux-head-20170113_belaroots_360.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/BELAROOTS - Магіла льва.mp3',
  },
  {
    id: 11,
    level: 1,
    name: 'Vinsent',
    species: 'Ток',
    description: 'Vinsent (сапраўднае імя - Дзмітрый Уладзіміравіч Папко) - беларускі спявак, хіп-хоп выканаўца, акцёр. Піша і выконвае песні на беларускай мове. Першапачаткова выступаў самастойна, у цяперашні час - у складзе калектыву, пад жывое музычнае суправаджэнне',
    image: 'https://naviny.belsat.eu/wp-content/uploads/2015/11/867678.png',
    audio: 'https://yazykovadaria.github.io/mysic//rap/vinsent.mp3',
  },
  {
    id: 12,
    level: 1,
    name: ' IQ48',
    species: 'Сьвятло ў цемры',
    description: 'IQ48 — гурт з Мінска, які спалучае ў сваёй творчасці рок, фанк і рэп. Першапачаткова гурт быў створаны восенню 2001 года як дуэт вакаліста Паўла «Фрэйда» Зыгмантовіча і гітарыста Яўгена «Буззы» Бузоўскага. Далей да іх далучыўся другі вакаліст Аляксандр "Эш" Ракавец, бас-гітарыст Канстанцін Калеснікаў і бубнач Антон "Сатана" Мацулевіч',
    image: 'https://lastfm.freetls.fastly.net/i/u/ar0/3843555589034a6d871a45d943082ae5.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rap/IQ48 - Сьвятло ў цемры (dizer.net).mp3',
  },
  {
    id: 13,
    level: 2,
    name: 'Бачу ўпершыню',
    species: 'Менск вясной',
    description: 'Бачу ўпершыню - беларускі поп-дуэт, заснаваны ў 2013 годзе вакалістам Алесем Сьнег і гітарыстам Уладзіславам Ляпяшынскім',
    image: 'https://sun9-8.userapi.com/impf/c834300/v834300931/1332a8/7WdjDfonF1A.jpg?size=604x403&quality=96&sign=78cf5c52c330be88bafeab42012cc1ba&type=album',
    audio: 'https://yazykovadaria.github.io/mysic//pop/Бачу Ўпершыню - Менск Вясной.mp3',
  },
  {
    id: 14,
    level: 2,
    name: 'Litesound',
    species: 'We Are The Heroes',
    description: 'Litesound — інтэрнацыянальны гурт, утвораны братамі Дзмітрыем і Уладзімірам Каракінымі ў Мінску ў 2005 годзе. У 2006 выпусцілі трэк "Solo Per Te", які трапіў у гарачую радыёратацыю як у Беларусі, так і ў Італіі. Litesound пяць разоў бралі ўдзел у нацыянальных адборах на конкурс "Еўрабачанне", тройчы праходзячы ў фінал і двойчы займаючы другое месца.',
    image: 'https://i1.sndcdn.com/avatars-000449391813-hfsa6f-t500x500.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/Litesound - We Are The Heroes (Евровидение 2012 Беларусь).mp3',
  },
  {
    id: 15,
    level: 2,
    name: 'Michael Soul',
    species: 'Humanize',
    description: 'Michael Soul (наст. імя - Міхаіл Сасуноў) - беларускі спявак і аўтар песень. Паўфіналіст восьмага сезона ўкраінскага шоу "Голас краіны". Таксама ўдзельнічаў у тэлепраектах "X-Фактар", "Хачу да Меладзэ" і "Ліга смеху". У 2018 годзе выпусціў міні-альбом "INSIDE", які складаецца з 5 англамоўных трэкаў.',
    image: 'https://yazykovadaria.github.io/mysic//pop/Michael Soul - Humanize.mp3',
    audio: 'https://yazykovadaria.github.io/mysic//pop/Michael Soul - Humanize.mp3',
  },
  {
    id: 16,
    level: 2,
    name: 'VAL',
    species: 'Да видна',
    description: 'VAL (наст. імя Валерыя Грыбусава) - беларуская спявачка, музыка і аўтар песень. Свой дэбютны сінгл "Хто ты ёсць" выпусціла 1 мая 2016 года. У студзені 2017 года адбыўся рэліз дэбютнага кліпа на сінгл "Вецер у сне"',
    image: 'https://esckaz.com/2020/JsiJ-6HwEu4.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/VAL-Da Vidna.mp3',
  },
  {
    id: 17,
    level: 2,
    name: 'NaviBand',
    species: 'Іншымі',
    description: 'NaviBand — беларускі музычны гурт з Мінска. Калектыў быў утвораны ў 2013 годзе і першапачаткова існаваў у выглядзе дуэта Ксеніі Жук і Арцёма Лук\'яненка пад назвай NAVI. Першая сумесна запісаная песня "Абдымі мяне" адразу ж стала радыёхітам у Беларусі, што і паслужыла пачаткам кар\'еры дуэта.',
    image: 'https://modernrock.ru/wp-content/uploads/2019/11/naviband.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/NaviBand_-_nshym_(musmore.com).mp3',
  },
  {
    id: 18,
    level: 2,
    name: 'Лиса',
    species: 'Не Відпускай',
    description: 'Ліса (сапраўдная імя Ліза Кастэнка) - буларуская спявачка і аўтар песень. Дэбютны сінгл "Сны" выйшаў у 2018 годзе, тады ж адбылася прэм\'ера міні-альбома "Бархат". У сакавіку 2020 выпусціла першы кліп, а ў красавіку адбыўся рэліз чацвёртага альбома - "Вельвет"',
    image: 'https://34mag.net/piarshak/media/posts/5e6a3f700398c-620-lisa-c.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pop/Лиса - Не Відпускай.mp3',
  },
  {
    id: 19,
    level: 3,
    name: 'N.R.M.',
    species: 'Паветраны шар',
    description: 'N.R.M. (белор. Незалежная Рэспубліка Мроя) — беларускі рок-гурт, заснаваны ў Менску ў 1994 годзе ўдзельнікамі рок-гурта «Мроя». Калектыў выконвае песні на беларускай мове, а пры напісанні тэкстаў часта выкарыстоўвае беларускую лацінку',
    image: 'https://lastfm.freetls.fastly.net/i/u/ar0/6ab59e63e61b448e9ab0585d6683b726.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/nrm-pavetrany-shar.mp3',
  },
  {
    id: 20,
    level: 3,
    name: 'Без бiлета',
    species: 'Адрес - планета Зямля',
    description: 'Без білета — беларускі рок-гурт, утвораны ў 1999 годзе ў Мінску. У ранняй творчасці музыкі спявалі на беларускай мове ў стылі фольк-рок, сумяшчаючы інды-рок з псіхадэлічнымі элементамі. У 2003-2006 гады асноўным стылем групы стаў індзі-рок. У 2007 годзе выйшаў альбом "Кіно" ў жанры поп-рок і альт-поп',
    image: 'https://modernrock.ru/wp-content/uploads/2018/08/bez-bileta.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/bez-bileta-adres---planeta-zemlya.mp3',
  },
  {
    id: 21,
    level: 3,
    name: 'J:МОРС',
    species: 'Піва',
    description: 'J:МОРС — беларускі рок-гурт, заснаваны ў 1999 годзе ў Мінску. Першапачаткова гурт называўся «No Logo». Гэта быў дуэт студэнтаў-юрыстаў Уладзіміра Пугача і Арцёма Лядоўскага. У 1999 годзе да іх далучыўся гітарыст Раман Арлоў, які прапанаваў змяніць назву. У выніку было абранае слова "морс", да якога дадалі літару "J". Існуе версія, што назва гурта звязана з імем гітарыста гурта «Deep Purple» Стывам Дж. Морсам',
    image: 'https://strigaproduction.com/wp-content/uploads/2022/04/J-MORS-JAN-20195463.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/j-mors-p-va-2003.mp3',
  },
  {
    id: 22,
    level: 3,
    name: 'Náka',
    species: 'Бяжы',
    description: 'Náka — беларускі рок-гурт, створаны ў 2004 г. у Мінску. У склад гурта ўвайшлі: Анастасія Шпакоўская (вакал, фартэпіяна), Юрый Сізоў (ударныя), Сяргей Шчурко (гітара). У 2005 г. выпусцілі першы live-кліп на песню "Хачу заснуць я"',
    image: 'https://studlive.by/wp-content/uploads/2016/01/naka-group.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/kopiya-naka-byazhy.mp3',
  },
  {
    id: 23,
    level: 3,
    name: 'Nizkiz',
    species: 'Блізка',
    description: 'Nizkiz — беларускі рок-гурт, які выконвае песні на рускай і беларускай мовах. Створана ў 2008 годзе ў Магілёве. Першы беларускі гурт, які выдаў альбом у лічбавым фармаце 3plet',
    image: 'https://img08.rl0.ru/afisha/e904x508p0x0f1815x1036q85i/s3.afisha.ru/mediastorage/e9/fe/b2c64be23c534953a2c0a35afee9.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/Nizkiz_-_Blzka_(musmore.com).mp3',
  },
  {
    id: 24,
    level: 3,
    name: 'Akute',
    species: 'Калi б я застаўся з табою',
    description: 'Akute (Акутэ) — беларускі рок-гурт, створаны ў 2008 годзе былымі ўдзельнікамі магілёўскай альтэрнатыўнай групы «Глюкі» Стасам Мытнікам і Раманам Жыгаравым. Першы выступ гурта адбыўся ў жніўні 2009 г. на фестывалі «Прыход». У лістападзе таго ж года на папулярным беларускамоўным сайце "Тузін Гітоў" адбылася прэм\'ера першага студыйнага запісу калектыву — песні "Адзіноцтва"',
    image: 'https://lastfm.freetls.fastly.net/i/u/ar0/3d9a5d047bb71c2c6365992174022be0.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//rock/akute-kali-b-ya-zasta-sya-z-taboyu.mp3',
  },
  {
    id: 25,
    level: 4,
    name: 'Касіяпея',
    species: 'Шчупальца з планеты "Х"',
    description: 'Касіяпея — беларускі электронны інды-поп-гурт, заснаваны ў 2001 годзе ў Мінску. Складаецца з трох чалавек, мае ў паслужным спісе тры афіцыйныя альбомы. Гурт адрознівае характэрнае пачуццё гумару, навукова-фантастычная і абсурдысцкая тэматыка. На сцэне яны, як правіла, выступаюць у мудрагелістых касцюмах і масках: адзіны атрыбут, які паўтараецца з вобраза ў вобраз — накладныя вусы, а астатнія дэталі канцэртнага гардэроба рэгулярна мяняюцца',
    image: 'https://sun9-45.userapi.com/impg/0zl8x0MmTDHcPXj3ct9Wek_M0ihmyBQz7SCozw/WOhRbxbtuBc.jpg?size=604x451&quality=95&sign=e1d391bf30240a1c6c3d5116c7e06e48&type=album',
    audio: 'https://yazykovadaria.github.io/mysic//indi/kassiopeya-schupal-ce-s-planety-h.mp3',
  },
  {
    id: 26,
    level: 4,
    name: 'САЮЗ',
    species: 'Офiсная',
    description: 'САЮЗ – беларускі гурт з Мінска, які склаўся з музыкаў, якія гралі ў Young and Dramatic, Applepicker і White Cave, The Toobes і «Валянцін Стракала. У 2018 выпусцілі дэбютны альбом - «Гэта ўсё зусім не тое»',
    image: 'https://34mag.net/piarshak/media/posts/5b28d96d300f6-620-soyuz.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//indi/СОЮЗ - Офисная.mp3',
  },
  {
    id: 27,
    level: 4,
    name: 'Маўчаць дома',
    species: 'Я не камуніст',
    description: 'Музычны праект "Маўчаць дома" быў утвораны ў Мінску ў 2017 годзе. Заснавальнікамі з\'яўляюцца Ягор Шкутко і Раман Камагорцаў. У красавіку 2017 года быў выдадзены дэбютны альбом пад назвай «З дахаў нашых дамоў», у які ўвайшлі 9 трэкаў. У 2018 годзе ў свет выходзіць альбом, які атрымаў назву "Этажы", які ўвайшоў у дваццатку лепшых альбомаў 2018 года па версіі брытанскіх крытыкаў.',
    image: 'https://img.the-village.ru/6qUhkpLABcMINbZGAoS-uuc3V2o8uEKxzH1GwsFIx0c/rs:fill:940:630/q:88/plain/2021/04/13/94IMG_9382.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//indi/Molchat_Doma_-_YA_ne_kommunist_(musmore.com).mp3',
  },
  {
    id: 28,
    level: 4,
    name: 'Palina',
    species: 'Месяц',
    description: 'Palina — творчы псеўданім беларускай выканаўцы Паліны Паланейчык. Нарадзілася ў Мінску ў красавіку 1994 года. Набыла вядомасць пасля перамогі на фестывалі "Бардаўская восень" у 2011 годзе. У 2012 годзе стала лаўрэатам прэміі Ultra-Music Awards у намінацыі "Адкрыццё года"',
    image: 'https://34mag.net/piarshak/content/editor_images/2020content/december/palina/PALINAKREMENDYNAMIT2.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//indi/Palina_-_Mesyac_(musmore.com).mp3',
  },
  {
    id: 29,
    level: 4,
    name: 'Intelligency',
    species: 'Malitva Belaruskaja',
    description: 'Intelligency  — беларускі шматмоўны музычны калектыў, які грае ў стылі тэхна-поп. Гурт заснаваны 9 мая 2013 года Усеваладам Доўбняй і Юрыем Тарасевічам. Першы студыйны альбом называўся Doloven і з\'явіўся ў канцы 2015 года',
    image: 'https://34mag.net/piarshak/media/posts/5edf7a4f24081-620-int-aug.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//indi/Intelligency_-_Malitva_Belaruskaja_(musmore.com).mp3',
  },
  {
    id: 30,
    level: 4,
    name: 'Dlina Volny',
    species: 'Do it',
    description: 'Dlina Volny — музычнае трыа з Мінска. Іграюць музыку ў жанрах нью-вэйв, пост-панк, сінт-поп, брут-поп. Гурт утварыўся ў 2016 годзе, у траўні таго ж года быў выпушчаны дэбютны рэліз «Neizmerima»',
    image: 'https://289118.selcdn.ru//media/artists/0/0/1/1488/20200504054601_large_dlina_volny.jpeg',
    audio: 'https://yazykovadaria.github.io/mysic//indi/Dlina_Volny_-_Do_It_(musmore.com).mp3',
  },
  {
    id: 31,
    level: 5,
    name: 'Пятля Прыхільнасьці',
    species: 'Аўтаматызм',
    description: 'Пятля Прыхільнасьці — беларуская пост-панк-група з Мінску. Была створана ў 2004 годзе вакалістам Іллём Чарапко-Самахвалавым і басістам Цімафеем Савіцкім на абломках папярэдняга праекта "Паліпы". Па словах Іллі, назва групы была ўзятая з савецкага антыалкагольнага плаката, які ён убачыў у паліклініцы. У 2009 г. выйшаў дэбютны альбом гурта пад назвай «Всем доволен»',
    image: 'https://trll.ru/uploads/2013/04/petp1.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pank/Petlya_Pristrastiya_-_Avtomatizm_(musmore.com).mp3',
  },
  {
    id: 32,
    level: 5,
    name: 'Разбітае сэрца пацана',
    species: 'БРСМ',
    description: 'Разбітае сэрца пацана («РСП») — беларускі музычны калектыў, заснаваны напрыканцы 1990-х у сценах Універсітэта культуры. Заснавальнікамі выступілі два студэнты: Дзяніс Тарасенка, вядомы па групе «Склеп» і Саша Маленькі (пасля вядомы як DJ Цім Карамыслаў). Гурт адрозніваецца тым, што піша і выконвае свае песні на трасянцы',
    image: 'https://cdn.3bls.eu/wp-content/uploads/2021/09/241085226_348843100277822_2432580024769766270_n-570x270.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pank/razbitoe_serdce_pacana_-_brsm_(z2.fm).mp3',
  },
  {
    id: 33,
    level: 5,
    name: 'Дай дарогу!',
    species: 'Про ментов',
    description: 'Дай дарогу! - беларускі панк-рок-гурт з Брэста. Была створана ў маі 1998 года ў Брэсце Юрыем «Кешай» Стыльскім (музыка, тэксты, гітара, вакал) і Васілём Капыловым (музыка, тэксты, вакал). У чэрвені 1999 г. выпусцілі дэбютны альбом«Зарубило!»',
    image: 'https://34mag.net/piarshak/media/posts/5e456ae0d79f0-5bae3737d66fc-620-dd.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pank/day-darogu-pro-mentov.mp3',
  },
  {
    id: 34,
    level: 5,
    name: 'Contra La Contra',
    species: 'Ты будешь счастлив и доволен',
    description: 'Contra La Contra — беларускі панк-рок-гурт, заснаваны ў 2001 годзе ў Гродне. За час свайго існавання гурт паспеў выпусціць дзве кружэлкі: дэма «Выйдзі на вуліцу» ў 2001 г. і альбом «Ні словы пра палітыку!» у 2002 г.',
    image: 'https://sun9-25.userapi.com/c4338/u68263679/130334231/x_566f6a93.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pank/Contra_La_Contra_Ty_budesh_schastliv_i_dovolen.mp3',
  },
  {
    id: 35,
    level: 5,
    name: 'Мутнаевока',
    species: 'Мутныя вочы',
    description: 'Мутнаевока — ббеларускі гурт, які выконвае песні на беларускай мове. Створана ў 2005 годзе ў Мінску. Музычны напрамак уключае ў сябе альтэрнатыўны рок, авангард-рок, пост-панк. Выхад дэбютнага альбома "Пошлы гламур" у 2010 годзе стаў адпраўной кропкай у творчасці гурта. Апроч гэтага альбома, у дыскаграфію гурта ўваходзяць ЕР «Усе мае сябры» (2011), ЕР «Ліхаманка» (2012) і ЕР «Апантаны» (2014)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/37/%D0%9C%D0%B2.jpg',
    audio: 'https://yazykovadaria.github.io/mysic//pank/mutnaevoka_-_mutnija_vochi_(z2.fm).mp3',
  },
  {
    id: 36,
    level: 5,
    name: 'Dzieciuki',
    species: 'Партызан',
    description: 'Dzieciuki — беларускі фолк-панк гурт, заснаваны ў 2012 годзе ў Гродне. Выконвае песні на беларускай мове ў асноўным на гістарычную тэматыку. Першы паўнавартасны альбом «Гарадзенскі гармідар» (з бел. — «Гродзенскі натоўп») выйшаў у лютым 2014 г. Перыядычна выступы гурта падвяргаюцца забаронам',
    image: 'https://rocketsmusic.ru/sites/default/files/styles/max_1300x1300/public/field/image/Dzieciuki.jpg.webp?itok=UObvym_x',
    audio: 'https://yazykovadaria.github.io/mysic//pank/Dzieciuki_-_Partyzan_(musmore.com).mp3',
  },
];
