start:
	npx webpack serve

dev:
	npx webpack

prod:
	npx webpack --node-env=production

public:
	npx webpack --node-env=production && npx gh-pages -d dist -e online-zoo

lint:
	npx eslint .

fix-lint:
	npx eslint . --fix
